services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        environment:
            - TZ=Etc/UTC
        ports:
            - "8443:8443"       # HTTPS
            - "8123:8123"       # DYNMAP
            - "19132:19132/udp" # BEDROCK
            - "25565:25565"     # MC SERVER
            - "25575:25575"     # RCON
        volumes:
            - /srv/crafty/backups:/crafty/backups
            - /srv/crafty/logs:/crafty/logs
            - /srv/crafty/servers:/crafty/servers
            - /srv/crafty/config:/crafty/app/config
            - /srv/crafty/import:/crafty/import
